In [1]:
import numpy as np
np.__version__


'1.19.5'

In [ ]:
#To create a header hove mouse over the edge of the line and click TEXT

In [ ]:
#Just get your coments around the code, to make it easier to go back to it

In [ ]:
#

In [ ]:
#Shift + enter skip to next block

HEADER? Hover mouse at the edge of the block line and click TEXT



In [ ]:
np?

Object `np` not found.


In [ ]:
numpy?

In [ ]:
L = list(range(10))

In [ ]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(L[0]) #tells you the type of that element
#Can have multiple types inside a same list


int

In [ ]:
type(L)

list

In [ ]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
LX2 = []
for c in L:
  LX2.append(str(c))
print(LX2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [ ]:
L3 = [True, "2", 3.0, 4]

In [ ]:
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
LX3 = []
for item in L3:
  LX3.append(type(item))
print(LX3)

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


In [ ]:
import array
l = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array([1,4.5,2,5,3])


array([1. , 4.5, 2. , 5. , 3. ])

In [ ]:
np.array([1,2,3,4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
LX4=[]
for i in [2,4,6]:
  LX4


In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((10,5) dtype=float) #row first,column second

row first, column second on a MAtrix /\





In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
myArray = np.full((3,5),3.14)
type(myArray)

numpy.ndarray

In [ ]:
type(myArray[1,2])

numpy.float64

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#Create an array of five values evenly spacedbetween 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#Create a 3X3 random array
np.random.random((3,3))

array([[0.20092982, 0.23494495, 0.07553509],
       [0.96168132, 0.95458874, 0.08865991],
       [0.84305532, 0.51383463, 0.49777805]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 0.98241799, -0.98470357, -0.5391178 ],
       [-0.89266832, -1.93592024,  1.03903986],
       [ 0.11109997,  1.60974138, -1.06496426]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[6, 5, 0],
       [7, 1, 9],
       [6, 9, 2]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros(10, dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.random.seed(0)
x1=np.random.randint(10,size = 6)
x2=np.random.randint(10, size=(3,4))
x3=np.random.randint(10, size=(3,4,5))

In [ ]:
x1

array([5, 8, 9, 5, 0, 0])

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [ ]:
print("x3 ndim", x3.ndim) #dimension
print("x3 shape", x3.shape)
print("x3 size", x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [ ]:
print("dtype: ", x3.dtype)

dtype:  int64


In [ ]:
print("itemsize:", x3.itemsize, " bytes")
print("nbytes:",x3.nbytes," bytes")

itemsize: 8  bytes
nbytes: 480  bytes


In [ ]:
x2[0,0] =12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x1[0]=3.14159
x1.dtype
x1

array([3, 0, 3, 3, 7, 9])

In [ ]:
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5] #display everything after the number 5

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]

array([4, 5, 6])

In [ ]:
x[::2]

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
x[5::-1]

array([5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]

array([5, 3, 1])

In [ ]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [ ]:
x2[:3,:2]

array([[12,  5],
       [ 7,  6],
       [ 1,  6]])

In [ ]:
x2[:3,:-1]

array([[12,  5,  2],
       [ 7,  6,  8],
       [ 1,  6,  7]])

In [ ]:
x2[::-1,::-1]


array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [ ]:
x2[::-1,::]

array([[ 1,  6,  7,  7],
       [ 7,  6,  8,  8],
       [12,  5,  2,  4]])

In [ ]:
print(x2[:,0])

[12  7  1]


In [ ]:
print(x2[0,:])

[12  5  2  4]


In [ ]:
x2_sub=x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [ ]:
x2_sub=x2[0:2,0:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [ ]:
x2_sub[0,0] = 99

In [ ]:
print(x2_sub)

[[99  5]
 [ 7  6]]


In [ ]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [ ]:
grid = np.arange(1,10)
print(grid)

[1 2 3 4 5 6 7 8 9]


In [ ]:
grid=np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
x.reshape((1,3))

array([[1, 2, 3]])

In [ ]:
x

array([1, 2, 3])

In [ ]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [ ]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [ ]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
#Verticaly stack array
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
y=np.array([[99],
           [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [7]:
import numpy as np

In [ ]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
test = np.arange(16)
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print('*************')
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
*************
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
np.random.seed(0)

In [ ]:
def compute_reciprocals(values):
  output=np.empty(len(values))
  for i in range(len(values)):
    output[i]= 1.0/values[i]
  return output

In [ ]:
values = np.random.randint(1,10,size=5)

In [ ]:
values

array([6, 1, 4, 4, 8])

In [ ]:
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
big_array = np.random.randint(1,100,size=1000000)

In [ ]:
%timeit compute_reciprocals(big_array)


1 loop, best of 5: 2.26 s per loop


In [ ]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
%timeit (1.0/big_array)
#Tells numpy that they will all be the same type, so function doesnt have to check for that

The slowest run took 5.24 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 5: 1.83 ms per loop


In [ ]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
x=np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
#Array arithmetic
x=np.arange(4)
print("x       =",x)
print("x + 5   =",x+5)
print("x - 5   =",x-5)
print("x * 2   =",x*2)
print("x / 2   =",x/2)
print("x // 2   =",x//2)#floor division

x       = [0 1 2 3]
x + 5   = [5 6 7 8]
x - 5   = [-5 -4 -3 -2]
x * 2   = [0 2 4 6]
x / 2   = [0.  0.5 1.  1.5]
x // 2   = [0 0 1 1]


In [ ]:
print("-x     =",-x)
print("x ** 2 =",x**2)
print("x % 2  =",x% 2)#remainder

-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


In [ ]:
0.5*x

array([0. , 0.5, 1. , 1.5])

In [ ]:
-(0.5*x+1)

array([-1. , -1.5, -2. , -2.5])

In [ ]:
#Standart order of operators
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

In [5]:
np.add(x,2)

array([2, 3, 4, 5])

In [6]:
x+2

array([2, 3, 4, 5])

In [8]:
x=np.array([-2,-1,0,1,2])
abs(x) #Ignores signal and truncates float, only display positive integer numbers

array([2, 1, 0, 1, 2])

In [9]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [10]:
x=([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [11]:
theta = np.linspace(0,np.pi,3)

In [12]:
print("theta          =",theta)
print("sin(theta)     =",np.sin(theta))
print("cos(theta)     =",np.cos(theta)) 
print("tan(theta)     =",np.tan(theta))

theta          = [0.         1.57079633 3.14159265]
sin(theta)     = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)     = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)     = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [14]:
#Inverse Trigonometric function
x=[-1,0,1]
print("x         =",x)
print("arcsin(x) =",np.arcsin(x))
print("arccos(x) =",np.arccos(x))
print("arctan(x) =",np.arctan(x))

x         = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [15]:
x = [1,2,3]
print("e^x   =",np.exp(x))
print("2^x   =",np.exp2(x))
print("2^x   =",np.power(2,x))
print("3^x   =",np.power(3,x))

e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
2^x   = [2 4 8]
3^x   = [ 3  9 27]


In [16]:
x=[1,2,3,4,10]
print("x     =",x)
print("ln(x) =",np.log(x))
print("log2(x) =",np.log2(x))
print("log10(x) =",np.log10(x))

x     = [1, 2, 3, 4, 10]
ln(x) = [0.         0.69314718 1.09861229 1.38629436 2.30258509]
log2(x) = [0.         1.         1.5849625  2.         3.32192809]
log10(x) = [0.         0.30103    0.47712125 0.60205999 1.        ]


In [17]:
x=[0,0.001,0.01,0.1]
print("exp(x)-1 =",np.expm1(x))

exp(x)-1 = [0.         0.0010005  0.01005017 0.10517092]


In [18]:
print("exp(x)-1 =",np.exp(x)-1)

exp(x)-1 = [0.         0.0010005  0.01005017 0.10517092]


In [19]:
print("log(1+x) = ",np.log1p(x))

log(1+x) =  [0.         0.0009995  0.00995033 0.09531018]


In [20]:
#y is x+1
y=[1,1.001,1.01,1.1]
print("log(1+x) =",np.log(y))

log(1+x) = [0.         0.0009995  0.00995033 0.09531018]


In [2]:
from scipy import special

In [4]:
x=[1,5,10]
print("gamma(x)    = ", special.gamma(x))
print("ln|gamma(x) =|",special.gammaln(x))
print("beta(x,2)   =",special.beta(x,2))

gamma(x)    =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x) =| [ 0.          3.17805383 12.80182748]
beta(x,2)   = [0.5        0.03333333 0.00909091]


In [8]:
x=np.array([0,0.3,0.7,1.0])
print("erf(x)  =",special.erf(x))#Error function
print("erfc(x) =",special.erfc(x))#error function complement
print("erfinv(x) =",special.erfinv(x))#error function inverse


erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [10]:
x=np.arange(5)
print("x=",x)
y=np.empty(5)
print("y=",y)
print("***********************")
print("y = x *10 is as follows:")
np.multiply(x,10,out=y)
print("y=",y)

x= [0 1 2 3 4]
y= [0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
***********************
y = x *10 is as follows:
y= [ 0. 10. 20. 30. 40.]


In [13]:
y=np.zeros(10)
print("y=",y)
print("***********")
z=np.power(2,x)
print("z=",z)
print("****************")
np.power(2,x,out=y[::2])
print("y=",y)

y= [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
***********
z= [ 1  2  4  8 16]
****************
y= [ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [14]:
x=np.arange(1,6)
print("x=",x)
np.add.reduce(x)

x= [1 2 3 4 5]


15

In [15]:
np.multiply.reduce(x)

120

In [5]:
np.add.accumulate(x)

array([ 1,  6, 16])

In [6]:
np.multiply.accumulate(x)

array([ 1,  5, 50])

In [8]:
x=np.arange(1,6)
print(x)

[1 2 3 4 5]


In [9]:
np.multiply(x,x)

array([ 1,  4,  9, 16, 25])

In [10]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [20]:
import numpy as np
L=np.random.random(100)
print("L =",L)
sum(L)

L = [0.90473819 0.99437912 0.01183098 0.68551358 0.84030017 0.08454655
 0.42316249 0.31187308 0.54242919 0.43347444 0.47748873 0.35364436
 0.3800556  0.35773893 0.10221066 0.84908209 0.01736352 0.7481011
 0.68978374 0.37999371 0.37021813 0.49020575 0.19710301 0.39311555
 0.35686748 0.22303432 0.63349221 0.32630787 0.82378534 0.53462054
 0.9141448  0.49409286 0.61727797 0.84008374 0.17048402 0.71122781
 0.21161678 0.78429631 0.50750269 0.74121894 0.34878333 0.59018175
 0.6682908  0.39868598 0.49609123 0.07236881 0.29070277 0.27153379
 0.33744688 0.36281297 0.81724833 0.48013337 0.80656486 0.88795203
 0.89757084 0.40869495 0.73161759 0.1530553  0.68400947 0.58579913
 0.09904064 0.48272525 0.22852302 0.20999768 0.81019551 0.93517611
 0.01177823 0.11569713 0.35967618 0.75386062 0.72356988 0.50746901
 0.95725212 0.96407218 0.98044356 0.3724788  0.1247599  0.96851225
 0.2869424  0.13833412 0.87348368 0.79126879 0.47178522 0.98880931
 0.13846755 0.77657207 0.069518   0.3196033  0.8123893  0.4

50.52304792692438

In [21]:
np.sum(L)

50.5230479269244

In [22]:
big_array=np.random.rand(1000000)
print("Python Sum")
%timeit sum(big_array)
print("NumPy Sum")
%timeit np.sum(big_array)

Python Sum
1 loop, best of 5: 162 ms per loop
NumPy Sum
The slowest run took 21.61 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 360 µs per loop


In [23]:
#Python
min(big_array), max(big_array)

(1.383154254464003e-07, 0.9999989169098509)

In [24]:
#NumPy
np.min(big_array), np.max(big_array)

(1.383154254464003e-07, 0.9999989169098509)

In [25]:
print("Python min")
%timeit min(big_array)
print("NunPy min")
%timeit np.min(big_array)

Python min
10 loops, best of 5: 104 ms per loop
NunPy min
1000 loops, best of 5: 407 µs per loop


In [27]:
#NumPy shortcut
print(big_array.min(), big_array.max(), big_array.sum())

1.383154254464003e-07 0.9999989169098509 499973.35640920285


In [28]:
%timeit big_array.min()

1000 loops, best of 5: 413 µs per loop


In [29]:
M=np.random.random((3,4))
print(M)

[[0.31755853 0.81903161 0.7385321  0.29089875]
 [0.12049872 0.20031058 0.5329132  0.01052164]
 [0.58965858 0.71649317 0.1086265  0.16730281]]


In [30]:
M.sum()

4.6123461941737345

In [31]:
M.min(axis=0)

array([0.12049872, 0.20031058, 0.1086265 , 0.01052164])

In [32]:
x = np.array([[1,1],[1,np.nan]])
np.sum(x)

nan

In [33]:
x=np.array([[1,1],[1,np.nan]])
np.nansum(x)

3.0

In [46]:
import pandas as pd

In [51]:
data = pd.read_csv("president_heights.csv")
data

order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [52]:
#Data head only shows first 5 results of table
data.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183